# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://andrewkeane-jci.github.io/nbdev_start/"

git_url = "https://github.com/andrewkeane-jci/nbdev_start/tree/{branch}/"

def custom_doc_links(name): return None
